In [57]:
# Importing required libraries

import pandas as pd

#reading dataset
data = pd.read_csv("crx.data" , header = None) 

data.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [58]:
# Dataset summary

print(data.describe())
print("\n")
print(data.info())

# Checking missing data
data.head(10)

               2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
0     690 non-null object
1     690 non-null object
2     690 non-null float64
3     690 non-null object
4     690 non-null object
5     690 non-null object
6     690 non-null object
7     690 non-null float64
8     690 non-null object
9     690 non-null object
10    690 non-null int64
11    690 non-null object
12    690 non-null object
13    690 non-null object
14    690 non-null int64

0      1       2  3  4   5  6      7  8  9   10 11 12     13     14 15
0  b  30.83   0.000  u  g   w  v  1.250  t  t   1  f  g  00202      0  +
1  a  58.67   4.460  u  g   q  h  3.040  t  t   6  f  g  00043    560  +
2  a  24.50   0.500  u  g   q  h  1.500  t  f   0  f  g  00280    824  +
3  b  27.83   1.540  u  g   w  v  3.750  t  t   5  t  g  00100      3  +
4  b  20.17   5.625  u  g   w  v  1.710  t  f   0  f  s  00120      0  +
5  b  32.08   4.000  u  g   m  v  2.500  t  f   0  t  g  00360      0  +
6  b  33.17   1.040  u  g   r  h  6.500  t  f   0  t  g  00164  31285  +
7  a  22.92  11.585  u  g  cc  v  0.040  t  f   0  f  g  00080   1349  +
8  b  54.42   0.500  y  p   k  h  3.960  t  f   0  f  g  00180    314  +
9  b  42.50   4.915  y  p   w  v  3.165  t  f   0  t  g  00052   1442  +

In [59]:
data.tail(10)

0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [60]:
data.tail(20)

0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
670  b  47.17   5.835  u  g   w   v  5.500  f  f   0  f  g  00465  150  -
671  b  25.83  12.835  u  g  cc   v  0.500  f  f   0  f  g  00000    2  -
672  a  50.25   0.835  u  g  aa   v  0.500  f  f   0  t  g  00240  117  -
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [61]:
# Importing numpy library
import numpy as np

# Replacing non-standard data with NaN
data = data.replace( "?" , np.NaN)

# Checking if the values are replaced correctly
data.tail(20)

0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
670    b  47.17   5.835  u  g   w   v  5.500  f  f   0  f  g  00465  150  -
671    b  25.83  12.835  u  g  cc   v  0.500  f  f   0  f  g  00000    2  -
672    a  50.25   0.835  u  g  aa   v  0.500  f  f   0  t  g  00240  117  -
673  NaN  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674    a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675    a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676    a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677    b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678    a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679    a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680    b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681    b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682    b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683    b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684    b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685    b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686    a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687    a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688    b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689    b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [62]:
# Replacing NaN values in numeric variables with mean values for that variable
data.fillna(data.mean(), inplace=True)

# Let us check if the numeric variables have any missing values
data.isna().sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

In [63]:
#the character variables still have NaN values
data.tail(20)

0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
670    b  47.17   5.835  u  g   w   v  5.500  f  f   0  f  g  00465  150  -
671    b  25.83  12.835  u  g  cc   v  0.500  f  f   0  f  g  00000    2  -
672    a  50.25   0.835  u  g  aa   v  0.500  f  f   0  t  g  00240  117  -
673  NaN  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674    a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675    a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676    a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677    b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678    a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679    a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680    b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681    b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682    b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683    b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684    b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685    b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686    a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687    a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688    b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689    b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [64]:
# Creating a loop to run on character variables to replace NaN values with most frequent values in that variable
for i in data:
    # if the variable is object type
    if data[i].dtypes == 'object':
        # replace with the most frequent value
        data = data.fillna(data[i].value_counts().index[0])

# Let us check if any variables have any missing values
data.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [65]:
#Converting non-numeric data into numeric data using LabelEncoder

from sklearn import preprocessing

encode = preprocessing.LabelEncoder()

#extracting data types for each column and performing numeric transformation
for i in data:
    if data[i].dtypes =='object':
        data[i]=encode.fit_transform(data[i])

In [66]:
#lets check if transformation has worked correctly
data.tail(20)

0    1       2   3   4   5   6      7   8   9   10  11  12   13   14  15
670   1  275   5.835   2   1  13   8  5.500   0   0   0   0   0  145  150   1
671   1  104  12.835   2   1   3   8  0.500   0   0   0   0   0    0    2   1
672   0  295   0.835   2   1   0   8  0.500   0   0   0   1   0   84  117   1
673   1  140   2.000   3   3   5   4  2.000   0   0   0   0   0   89   17   1
674   0  214   2.500   2   1   7   4  0.210   0   0   0   0   0   90  246   1
675   0  248   1.040   2   1   0   8  0.665   0   0   0   0   0   84  237   1
676   0  153  10.665   2   1  11   4  0.085   0   1  12   1   0   40    3   1
677   1   36   7.250   2   1  10   8  0.040   0   1   1   0   0   31    1   1
678   0   20  10.210   2   1   6   3  0.000   0   0   0   0   0    0   50   1
679   0   42   1.250   2   1   2   8  0.000   0   0   0   0   0    0    0   1
680   1   37   0.290   2   1   9   8  0.290   0   0   0   0   0   96  364   1
681   1  125   1.000   3   3   4   4  3.000   0   0   0   0   0   60  537   1
682   1   12   3.290   2   1   7   8  0.335   0   0   0   1   0   44    2   1
683   1  208   0.750   3   3   4   8  0.585   0   0   0   0   0   84    3   1
684   1  240   3.290   2   1  10   8  3.500   0   0   0   1   2  129    0   1
685   1   52  10.085   3   3   5   4  1.250   0   0   0   0   0   90    0   1
686   0   71   0.750   2   1   2   8  2.000   0   1   2   1   0   67  394   1
687   0   97  13.500   3   3   6   3  2.000   0   1   1   1   0   67    1   1
688   1   20   0.205   2   1   0   8  0.040   0   0   0   0   0   96  750   1
689   1  197   3.375   2   1   2   4  8.290   0   0   0   1   0    0    0   1

In [67]:
#creating correlation matrix for our data to check correlation of variables and possibility of multicollinearity
corr = data.corr()

In [68]:
import matplotlib.pyplot as plt
import seaborn as sns

mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(220, 10, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, mask=mask, cmap=cmap, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})

In [69]:
#We can observe feature 4,3 and 9,10 are highly correlated, this might lead to multicollinearity
#we can also observe that feature 0,6,11 have very less correlation with variable 15 which is our dependent variable

# So we decide to drop features 0,4,6,9,11 and convert the DataFrame to a NumPy array

data = data.drop([0,4,6,9,11],axis=1)

corr = data.corr()

import matplotlib.pyplot as plt
import seaborn as sns

mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(220, 10, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, mask=mask, cmap=cmap, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})



In [70]:
#Now we will scale the data using MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

data = data.values

# We will split independent variables(x) and dependent variable(y)
x = data[:,0:9] 
y = data[:,10]

#Scaling the data
scale = MinMaxScaler(feature_range=(0,1))
new_x = scale.fit_transform(data)

In [71]:
#let check how our data looks like now
print(data)

[[1.560e+02 0.000e+00 2.000e+00 ... 6.800e+01 0.000e+00 0.000e+00]
 [3.280e+02 4.460e+00 2.000e+00 ... 1.100e+01 5.600e+02 0.000e+00]
 [8.900e+01 5.000e-01 2.000e+00 ... 9.600e+01 8.240e+02 0.000e+00]
 ...
 [9.700e+01 1.350e+01 3.000e+00 ... 6.700e+01 1.000e+00 1.000e+00]
 [2.000e+01 2.050e-01 2.000e+00 ... 9.600e+01 7.500e+02 1.000e+00]
 [1.970e+02 3.375e+00 2.000e+00 ... 0.000e+00 0.000e+00 1.000e+00]]


In [89]:
# Now we will split the data into train(80%) and test(20%) set to build a model

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [90]:
#Now we will build our first model using KNN

from sklearn.neighbors import KNeighborsClassifier  

kmodel = KNeighborsClassifier(n_neighbors=5)  
kmodel.fit(x_train, y_train) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [91]:
# To check our model performance, we will check the confusion matrix ie, True +ve,-ve and False +ve,-ve

from sklearn.metrics import confusion_matrix

predicted = kmodel.predict(x_test)
modelscore = kmodel.score(x_test,y_test)

print("Accuracy: ", modelscore)

print(confusion_matrix(y_test,predicted))

Accuracy:  0.6618357487922706
[[49 37]
 [33 88]]


In [92]:
#Now we will build our second model using Logistic Regression

from sklearn.linear_model import LogisticRegression

# Initialize a Logistic Regression classifier and fit model on train set

lmodel = LogisticRegression()

lmodel.fit(x_train,y_train)

C:\Users\jspar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [93]:
# Now again we predict the values of dependent variable using new model and check model accuracy
predicted = lmodel.predict(x_test)

print("Accuracy: ", lmodel.score(x_test,y_test))

print(confusion_matrix(y_test,predicted))

Accuracy:  0.8502415458937198
[[78  8]
 [23 98]]


In [94]:
#checking the ROC curve
from sklearn.metrics import roc_curve

fpr,tpr,thresholds = roc_curve(y_test , predicted)

plt.plot([0,1], [0,1], 'k--')
plt.plot(fpr,tpr)
plt.xlabel("False positive")
plt.ylabel("True positive")
plt.show()

In [100]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, roc_auc_score, precision_score
THRESHOLD = 0.4
preds = np.where(lmodel.predict_proba(x_test)[:,1] > THRESHOLD, 1, 0)

pd.DataFrame(data=[accuracy_score(y_test, preds), recall_score(y_test, preds),
                   precision_score(y_test, preds), roc_auc_score(y_test, preds)], 
             index=["accuracy", "recall", "precision", "roc_auc_score"])

0
accuracy       0.869565
recall         0.851240
precision      0.919643
roc_auc_score  0.873294